### PR TITLE
security related shell script enhancements

### PR DESCRIPTION
**Pull request by humaknlght**

### CODE REVIEW

**Comment by gleclaire** [comment]
These scripts are no longer used as Findbugs is deployed as part of their project which is separate from this.

**Comment by humaknlght** [comment]
Ah okay.  If they are no longer being used, can they be deemed so we do not
create this type of confusion in the future?

On Thu, Oct 22, 2015, 5:29 AM Garvin Leclaire <notifications@github.com>
wrote:

> These scripts are no longer used as Findbugs is deployed as part of their
> project which is separate from this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gleclaire/findbugs-maven-plugin/pull/29#issuecomment-150205674>
> .
>
-- 

Eric

**Comment by gleclaire** [comment]
I will remove them

Regards,


Garvin LeClaire
garvin.leclaire@gmail.com

**Comment by humaknlght** [comment]
Great.

On Tue, Oct 27, 2015, 11:43 AM Garvin Leclaire <notifications@github.com>
wrote:

> I will remove them
>
> Regards,
>
>
> Garvin LeClaire
> garvin.leclaire@gmail.com
>
> On Tue, Oct 27, 2015 at 1:14 PM, humaknlght <notifications@github.com>
> wrote:
>
> > Ah okay. If they are no longer being used, can they be deemed so we do
> not
> > create this type of confusion in the future?
> >
> > On Thu, Oct 22, 2015, 5:29 AM Garvin Leclaire <notifications@github.com>
> > wrote:
> >
> > > These scripts are no longer used as Findbugs is deployed as part of
> their
> > > project which is separate from this.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/gleclaire/findbugs-maven-plugin/pull/29#issuecomment-150205674
> > >
> > > .
> > >
> > --
> >
> > Eric
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/gleclaire/findbugs-maven-plugin/pull/29#issuecomment-151574056
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gleclaire/findbugs-maven-plugin/pull/29#issuecomment-151606203>
> .
>
-- 

Eric

**Pull request closed without merging**
