### PR TITLE
 findbugs:gui doesn't load plugins #37

### PR DESCRIPTION
**Pull request by VsevolodGolovanov**
GUI gets configured plugins

### CODE REVIEW

**Comment by gleclaire** [comment]
does not run all the integrations tests.  I will have to look into it further to get exact details.

**Comment by VsevolodGolovanov** [comment]
Tried running the tests with `mvn -Prun-its clean install`, they fail the same way with and without my changes:
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-invoker-plugin:2.0.0:run (integration-test) on project findbugs-maven-plugin: 37 builds failed. See console output above for details. -> [Help 1]`
But maybe they just fail on Windows?
Or with maven-invoker-plugin 2.0.0? I updated the version because of https://issues.apache.org/jira/browse/MNG-5792

[with_changes.txt](https://github.com/gleclaire/findbugs-maven-plugin/files/286555/with_changes.txt)
[without_changes.txt](https://github.com/gleclaire/findbugs-maven-plugin/files/286556/without_changes.txt)

**Comment by marcosscriven** [comment]
Just noticed this issue as well. Is this ready to merge?

**Comment by VsevolodGolovanov** [comment]
I'll check the itests on Linux when I have the time, in a week probably.

**Comment by VsevolodGolovanov** [comment]
Looked at this again. Figured out, that I needed to download the findbugs sources manually for ITests, because googlecode is unavailable. Downloaded the 1.3.9 sources. Run the tests on master (without my changes).
[master.txt](https://github.com/gleclaire/findbugs-maven-plugin/files/356071/master.txt)

```
[INFO] Build Summary:
[INFO]   Passed: 18, Failed: 27, Errors: 0, Skipped: 0
```

Most failures are off by one errors when comparing findbugs.xml and findbugsXml.xml files, e.g.:

```
[INFO] Building: check\pom.xml
[INFO] ..FAILED (14.3 s)
[INFO]   The post-build script did not succeed. Expression: (xdocErrors == findbugsXmlErrors). Values: xdocErrors = 33, findbugsXmlErrors = 34
```

Checked the files at target/it/check/target, and the difference is that findbugsXml.xml has this additional bug instance:

```
type='HE_SIGNATURE_DECLARES_HASHING_OF_UNHASHABLE_CLASS' 
...
<LongMessage>UseOfNonHashableClassInHashDataStructure doesn't define a hashCode() method but it is used in a hashed context in UseOfNonHashableClassInHashDataStructure$UMap</LongMessage>
```

@gleclaire, is there some secret to running the tests? :) Or is there an unrelated problem?

**Comment by VsevolodGolovanov** [comment]
I'm still willing to do the work, if something needs to be done. I just wish @gleclaire would explain, what's wrong or how to run tests or something...

**Comment by gleclaire** [comment]
It doesn't work for reports on multi-module projects

**Comment by VsevolodGolovanov** [comment]
@gleclaire, as in during the site lifecycle? I'll check it out.

**Comment by hazendaz** [comment]
@VsevolodGolovanov All integration tests run now.  Can you check out the issue with GUI again to see if this issue still exists?

**Comment by VsevolodGolovanov** [comment]
Verified that the issue is still present in the current 3.0.6-SNAPSHOT.

Successfully ran itests without my changes, and got 7 failures with my changes - now I can see the problems and fix them.

**Comment by hazendaz** [comment]
@VsevolodGolovanov Is this something you might be able to address this week?  I'm pretty sure same issue was raised against spotbugs-maven-plugin.  I'm releasing that but if this could be fixed soon, I can incorporate that fix.  We are pending 3.1.0 release there so I'll hold on a while in case this can be fixed.

**Comment by hazendaz** [comment]
Same issue reported here potentially [here](https://github.com/spotbugs/spotbugs-maven-plugin/issues/10}.  Would be great to get this fixed on this PR and moving this week 👍

**Comment by VsevolodGolovanov** [comment]
Rebased on the current master and fixed the issue with ResourceHelper missing the resourceManager. All itests pass.

**Comment by gleclaire** [comment]
Thanks for the update

**Pull request merged**
